version: '3.8'

services:
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - payment-service
      - inventory-service
      - shipping-service
    networks:
      - microservices-network

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network

  shipping-service:
    build:
      context: ./shipping-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge